site_name: Sandalen met sokken
site_url: https://sandalenmetsokken.nl/
site_author: Chinou van Maris, Teun Engels
site_description: >-
  Sandalen met Sokken (Sandals with Socks in English) provides guides and cheatsheets for all kind of IT related topics. We have guides for programming languages, DevOps, Cloud, and more.


# Copyright
copyright: Copyright &copy; 2022  |  Chinou & Teun

repo_url: https://github.com/chinouvm/sandalenmetsokken-wiki

repo_name: Github

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logoblue.png
  favicon: img/favicon.png
  homepage: https://sandalenmetsokken.nl/
  features:
    - navigation.top
    - navigation.tabs
  palette:
    scheme: slate
    primary: blue

  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Cheatsheets:
      - Python:
          - Python Programming: Python.md
          - Python Installing: PyInstalling.md
      - Git: Git.md
  - Guides:
      - How to contribute: howtocontribute.md
      - API:
          - API Basics: BasicsAPI.md
          - FastAPI: FastAPI.md
      - C++: CPP.md
      - Docker:
          - Installation: DockerInstall.md
  - Glossary: Glossary.md
  - Contributors: Contributors.md
  - Supporters: Supporters.md

extra_css:
  - stylesheets/extra.css

plugins:
  - tags
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chinouvm/sandalenmetsokken-wiki
      name: The Github Repo of this Website
    - icon: fontawesome/solid/money-check-dollar
      link: https://ko-fi.com/sandalenmetsokken
      name: Our ko-fi link for donations!
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - meta
  - pymdownx.details
