site_name: Sandalen met sokken!
site_url: https://sandalenmetsokken.nl/
theme:
  name: material
  logo: img/logo.png
  homepage: https://sandalenmetsokken.nl/
  features:
    - navigation.top
  palette:
    scheme: slate
    primary: blue
nav:
  - Home: index.md
  - Cheatsheets:
      - Python:
          - Python Programming: Python.md
          - Python Installing: PyInstalling.md
      - API:
          - API Basics: BasicsAPI.md
          - FastAPI: FastAPI.md

      - Git: Git.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html
