name: gh-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: GH Pages auto deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Mkdocs deploy
        run: |
          git pull
          mkdocs gh-deploy

      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC: 'CNAME'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
